/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package users.common;


import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
import java.sql.*;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.Map;
import login.Conexion;


import javax.swing.table.DefaultTableCellRenderer;

public abstract class AsistenciaPanel extends JPanel {
   
    protected Connection conect;
    protected int usuarioId;
    protected LocalDate fecha;
    protected JTable tablaAsistencia;
    protected DefaultTableModel tableModel;
    protected Map<String, Color> colorEstados;
    
    public AsistenciaPanel(){
    super();
    inicializarColores();
    }
    
    private void inicializarColores(){
    colorEstados = new HashMap<>();
        colorEstados.put("P", new Color(144, 238, 144));  // Verde claro
        colorEstados.put("A", new Color(255, 182, 193));  // Rojo claro
        colorEstados.put("T", new Color(255, 255, 153));  // Amarillo claro
        colorEstados.put("AP", new Color(255, 218, 185)); // Naranja claro
        colorEstados.put("NC", Color.WHITE);              // No corresponde
    }
    
    protected void configurarTabla(){
    if (tableModel == null){
    tableModel= new DefaultTableModel();
    }
    tableModel.addColumn("Alumno");
    tableModel.addColumn("DNI");
    tableModel.addColumn("Estado");
    
    if (tablaAsistencia != null){
        tablaAsistencia.setModel(tableModel);
    }
    
    }
    
    protected abstract void cargarAsistencias();
    protected abstract void guardarAsistencias();
    protected abstract boolean puedeEditarCelda(int row, int column);
    
    protected void inicializarBase(int usuarioId) {
        this.usuarioId = usuarioId;
        this.fecha = LocalDate.now();
        this.tableModel = new DefaultTableModel();
        if (tablaAsistencia != null) {
            tablaAsistencia.setModel(tableModel);
        }
        // Inicializar conexión
        this.conect = Conexion.getInstancia().getConexion();
        if (this.conect == null) {
            JOptionPane.showMessageDialog(this, "Error de conexión.");
            return;
        }
        inicializarColores();
        configurarTabla();
    }
    
    private void inicializarComponentes() {
        conect = Conexion.getInstancia().getConexion();
        inicializarColores();
    }
    
   
    
    
    // Clase interna para el renderizado de celdas
    protected class AsistenciaCellRenderer extends DefaultTableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            if (!isSelected && column >= 2) {
                String estado = value != null ? value.toString() : "NC";
                c.setBackground(colorEstados.getOrDefault(estado, Color.WHITE));
            }
            
            return c;
        }
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
