/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.java.views.users.Attp.menu;

import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import main.java.database.Conexion;
import main.java.views.users.common.VentanaInicio;

/**
 *
 * @author nico_
 */
public class PrestamosPanel extends javax.swing.JPanel {

    // Conexión a la base de datos
    private Connection conect;
    
    // Referencia a la ventana principal
    private VentanaInicio ventanaPrincipal;
    
    // ID del usuario ATTP
    private int attpId;

    /**
     * Constructor del panel de Préstamos.
     *
     * @param ventanaPrincipal Referencia a la ventana principal para navegación
     * @param attpId ID del usuario ATTP
     */
    public PrestamosPanel(VentanaInicio ventanaPrincipal, int attpId) {
        this.ventanaPrincipal = ventanaPrincipal;
        this.attpId = attpId;
        initComponents();
        probar_conexion();
        mostrardatos();
    }

    /**
     * Verifica la conexión a la base de datos.
     */
    private void probar_conexion() {
        conect = Conexion.getInstancia().verificarConexion();
        if (conect == null) {
            JOptionPane.showMessageDialog(this, "Error de conexión.");
        }
    }

    /**
     * Carga y muestra los datos de préstamos en la tabla.
     */
    public void mostrardatos() {
        probar_conexion();

        // Crear modelo de tabla
        DefaultTableModel tablitasPre = new DefaultTableModel();
        tablitasPre.addColumn("Netbook_ID");
        tablitasPre.addColumn("Fecha_Prestamo");
        tablitasPre.addColumn("Fecha_Devolucion");
        tablitasPre.addColumn("Hora_Prestamo");
        tablitasPre.addColumn("Hora_Devolucion");
        tablitasPre.addColumn("Curso");
        tablitasPre.addColumn("Alumno");
        tablitasPre.addColumn("Tutor");
        TablasPre.setModel(tablitasPre);
        Statement vertablasPre;
        String[] datos_Pre = new String[8];
        try {
            vertablasPre = conect.createStatement();
            ResultSet mostrarsPre = vertablasPre.executeQuery("SELECT * FROM prestamos");
            while (mostrarsPre.next()) {
                datos_Pre[0] = mostrarsPre.getString(2);
                datos_Pre[1] = mostrarsPre.getString(3);
                datos_Pre[2] = mostrarsPre.getString(4);
                datos_Pre[3] = mostrarsPre.getString(5);
                datos_Pre[4] = mostrarsPre.getString(6);
                datos_Pre[5] = mostrarsPre.getString(7);
                datos_Pre[6] = mostrarsPre.getString(8);
                datos_Pre[7] = mostrarsPre.getString(9);
                tablitasPre.addRow(datos_Pre);
            }
        } catch (SQLException e) {
            System.err.println("Error al cargar datos de préstamos: " + e.getMessage());
        }
        TablasPre.setModel(tablitasPre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablasPre = new javax.swing.JTable();
        Boton_Volver4 = new javax.swing.JButton();
        Boton_Modificar2 = new javax.swing.JToggleButton();
        Boton_ingresar = new javax.swing.JToggleButton();
        Boton_borrar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Registros de prestamos realizados");

        TablasPre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablasPre);

        Boton_Volver4.setText("Volver");
        Boton_Volver4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Volver4ActionPerformed(evt);
            }
        });

        Boton_Modificar2.setText("Modificar");
        Boton_Modificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Modificar2ActionPerformed(evt);
            }
        });

        Boton_ingresar.setText("Ingresar");
        Boton_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ingresarActionPerformed(evt);
            }
        });

        Boton_borrar.setText("Borrar");
        Boton_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_borrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(408, 408, 408)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Boton_borrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Boton_Volver4)
                .addGap(18, 18, 18)
                .addComponent(Boton_Modificar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Boton_ingresar)
                .addGap(351, 351, 351))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_Volver4)
                    .addComponent(Boton_Modificar2)
                    .addComponent(Boton_ingresar)
                    .addComponent(Boton_borrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_Volver4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Volver4ActionPerformed
       ventanaPrincipal.restaurarVistaPrincipal();
    }//GEN-LAST:event_Boton_Volver4ActionPerformed

    private void Boton_Modificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Modificar2ActionPerformed
     Statement statement = null;
        try {
            statement = conect.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM prestamos");
            while (resultSet.next()) {
                String Prestamo_ID = resultSet.getString("Prestamo_ID");
                String Netbook_ID = resultSet.getString("Netbook_ID");
                String Fecha_Prestamo = resultSet.getString("Fecha_Prestamo");
                String Fecha_Devolucion = resultSet.getString("Fecha_Devolucion");
                String Hora_Prestamo = resultSet.getString("Hora_Prestamo");
                String Hora_Devolucion = resultSet.getString("Hora_Devolucion");
                String Curso = resultSet.getString("Curso");
                String Alumno = resultSet.getString("Alumno");
                String Tutor = resultSet.getString("Tutor");

                try (FileWriter EscrituraInicial = new FileWriter("Registros.txt", true)) {
                    EscrituraInicial.write("\n");
                    EscrituraInicial.write("Datos iniciales de prestamos: " + Prestamo_ID + "|" + Netbook_ID + "|" + Fecha_Prestamo + "|" + Fecha_Devolucion + "|" + Hora_Prestamo + "|" + Hora_Devolucion + "|" + Curso + "|" + Alumno + "|" + Tutor);
                    EscrituraInicial.write("\n");
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Error al escribir en el archivo: " + e.getMessage());
                }
            }
        } catch (SQLException ex) {
            System.err.println("Error al consultar préstamos: " + ex.getMessage());
        }

        int fila = TablasPre.getSelectedRow();

        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Seleccione el registro antes de apretar el botón");
            return;
        }

        String Netbook_ID = TablasPre.getValueAt(fila, 0).toString();
        String Fecha_Prestamo = TablasPre.getValueAt(fila, 1).toString();
        String Fecha_Devolucion = TablasPre.getValueAt(fila, 2).toString();
        String Hora_Prestamo = TablasPre.getValueAt(fila, 3).toString();
        String Hora_Devolucion = TablasPre.getValueAt(fila, 4).toString();
        String Curso = TablasPre.getValueAt(fila, 5).toString();
        String Alumno = TablasPre.getValueAt(fila, 6).toString();
        String Tutor = TablasPre.getValueAt(fila, 7).toString();
        
        try {
            PreparedStatement actu = conect.prepareStatement("UPDATE prestamos SET Fecha_Prestamo= '" + Fecha_Prestamo + "',Fecha_Devolucion = '" + Fecha_Devolucion
                    + "',Hora_Prestamo = '" + Hora_Prestamo + "',Hora_Devolucion = '" + Hora_Devolucion + "',Curso = '" + Curso + "',Alumno = '" + Alumno + "',Tutor = '" + Tutor + "' WHERE Netbook_ID = '" + Netbook_ID + "'");
            actu.executeUpdate();
            mostrardatos();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e + "No se pudo actualizar los datos");
            return;
        }
        
        JOptionPane.showMessageDialog(null, "¡Registro actualizado!");
        
        try (FileWriter Escritura = new FileWriter("Registros.txt", true)) {
            Escritura.write("\n");
            String Registro2 = ("Datos finales de prestamos: " + Netbook_ID + "|" + Fecha_Prestamo + "|" + Fecha_Devolucion + "|" + Hora_Prestamo + "|" + Hora_Devolucion + "|" + Curso + "|" + Alumno + "|" + Tutor);
            Escritura.write(Registro2);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error al escribir en el archivo: " + e.getMessage());
        }
    }//GEN-LAST:event_Boton_Modificar2ActionPerformed

    private void Boton_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ingresarActionPerformed
        
    }//GEN-LAST:event_Boton_ingresarActionPerformed

    private void Boton_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_borrarActionPerformed
        
    }//GEN-LAST:event_Boton_borrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Boton_Modificar2;
    private javax.swing.JButton Boton_Volver4;
    private javax.swing.JButton Boton_borrar;
    private javax.swing.JToggleButton Boton_ingresar;
    private javax.swing.JTable TablasPre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
