import { Router } from 'express';
import authRoutes from './authRoutes.js';
import userRoutes from './userRoutes.js';
import studentRoutes from './studentRoutes.js';
import courseRoutes from './courseRoutes.js';
import subjectRoutes from './subjectRoutes.js';
import gradeRoutes from './gradeRoutes.js';
import attendanceRoutes from './attendanceRoutes.js';
import assignmentRoutes from './assignmentRoutes.js';
import notificationRoutes from './notificationRoutes.js';
import configurationRoutes from './configurationRoutes.js';
import deviceRoutes from './deviceRoutes.js';
import scheduleRoutes from './scheduleRoutes.js';
import lessonBookRoutes from './lessonBookRoutes.js';
import roleRoutes from './roleRoutes.js';
import newsRoutes from './newsRoutes.js';
import galleryRoutes from './galleryRoutes.js';
import reportCardRoutes from './reportCardRoutes.js';
import registrationRoutes from './registrationRoutes.js';
import contactRoutes from './contactRoutes.js';
import publicPageRoutes from './publicPageRoutes.js';
import fileRoutes from './fileRoutes.js';
import cargoRoutes from './cargoRoutes.js';
import pendingSubjectRoutes from './pendingSubjectRoutes.js';
const router = Router();

router.use('/auth', authRoutes);
router.use('/usuarios', userRoutes);
router.use('/alumnos', studentRoutes);
router.use('/cursos', courseRoutes);
router.use('/materias', subjectRoutes);
router.use('/notas', gradeRoutes);
router.use('/asistencias', attendanceRoutes);
router.use('/trabajos', assignmentRoutes);
router.use('/notificaciones', notificationRoutes);
router.use('/news', newsRoutes);
router.use('/gallery', galleryRoutes);
router.use('/configuracion', configurationRoutes);
router.use('/dispositivos', deviceRoutes);
router.use('/horarios', scheduleRoutes);
router.use('/roles', roleRoutes);
router.use('/report-cards', reportCardRoutes);
router.use('/registrations', registrationRoutes);
router.use('/contact', contactRoutes);
router.use('/public/pages', publicPageRoutes);
router.use('/files', fileRoutes);
router.use('/libros-temas', lessonBookRoutes);
router.use('/cargos', cargoRoutes);
router.use('/materias-pendientes', pendingSubjectRoutes);

export default router;